# Generated by Django 5.0.7 on 2024-07-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Management', '0002_profile_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='image/default.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='room_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
